- name: download docker.sh using wget (python 2.7.6 breaks using get_url mod)
  command: wget -O /tmp/docker.sh https://get.docker.com/
  tags: docker

- name: install docker
  command: sh /tmp/docker.sh
  tags: docker

- name: add permissions to the user (os restart required to work)
  command: usermod -aG docker $USER
  tags: docker

- name: download docker-compose (python 2.7.6 breaks using get_url mod)
# command: wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)
  command: wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64
  tags: docker

- name: docker-compose exe permissions
  command: chmod +x /usr/local/bin/docker-compose
  tags: docker